# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: car_protobufs/lidar_proto.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='car_protobufs/lidar_proto.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x1f\x63\x61r_protobufs/lidar_proto.proto\"^\n\tStartStop\x12\x16\n\x0epublish_period\x18\x01 \x01(\x05\x12\x1f\n\x05state\x18\x02 \x01(\x0e\x32\x10.StartStop.State\"\x18\n\x05State\x12\x07\n\x03OFF\x10\x00\x12\x06\n\x02ON\x10\x01\")\n\tDataPoint\x12\r\n\x05range\x18\x01 \x01(\x05\x12\r\n\x05\x61ngle\x18\x02 \x01(\x01\"4\n\x04Scan\x12\x11\n\ttimestamp\x18\x01 \x01(\x05\x12\x19\n\x05scans\x18\x02 \x03(\x0b\x32\n.DataPoint\"\"\n\rHealthRequest\x12\x11\n\ttimestamp\x18\x01 \x01(\x05\"%\n\x0cHealthStatus\x12\x15\n\rhealthMessage\x18\x01 \x01(\tb\x06proto3')
)



_STARTSTOP_STATE = _descriptor.EnumDescriptor(
  name='State',
  full_name='StartStop.State',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OFF', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ON', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=105,
  serialized_end=129,
)
_sym_db.RegisterEnumDescriptor(_STARTSTOP_STATE)


_STARTSTOP = _descriptor.Descriptor(
  name='StartStop',
  full_name='StartStop',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='publish_period', full_name='StartStop.publish_period', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='state', full_name='StartStop.state', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _STARTSTOP_STATE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=129,
)


_DATAPOINT = _descriptor.Descriptor(
  name='DataPoint',
  full_name='DataPoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='range', full_name='DataPoint.range', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='angle', full_name='DataPoint.angle', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=131,
  serialized_end=172,
)


_SCAN = _descriptor.Descriptor(
  name='Scan',
  full_name='Scan',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='Scan.timestamp', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='scans', full_name='Scan.scans', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=174,
  serialized_end=226,
)


_HEALTHREQUEST = _descriptor.Descriptor(
  name='HealthRequest',
  full_name='HealthRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='HealthRequest.timestamp', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=228,
  serialized_end=262,
)


_HEALTHSTATUS = _descriptor.Descriptor(
  name='HealthStatus',
  full_name='HealthStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='healthMessage', full_name='HealthStatus.healthMessage', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=264,
  serialized_end=301,
)

_STARTSTOP.fields_by_name['state'].enum_type = _STARTSTOP_STATE
_STARTSTOP_STATE.containing_type = _STARTSTOP
_SCAN.fields_by_name['scans'].message_type = _DATAPOINT
DESCRIPTOR.message_types_by_name['StartStop'] = _STARTSTOP
DESCRIPTOR.message_types_by_name['DataPoint'] = _DATAPOINT
DESCRIPTOR.message_types_by_name['Scan'] = _SCAN
DESCRIPTOR.message_types_by_name['HealthRequest'] = _HEALTHREQUEST
DESCRIPTOR.message_types_by_name['HealthStatus'] = _HEALTHSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StartStop = _reflection.GeneratedProtocolMessageType('StartStop', (_message.Message,), dict(
  DESCRIPTOR = _STARTSTOP,
  __module__ = 'car_protobufs.lidar_proto_pb2'
  # @@protoc_insertion_point(class_scope:StartStop)
  ))
_sym_db.RegisterMessage(StartStop)

DataPoint = _reflection.GeneratedProtocolMessageType('DataPoint', (_message.Message,), dict(
  DESCRIPTOR = _DATAPOINT,
  __module__ = 'car_protobufs.lidar_proto_pb2'
  # @@protoc_insertion_point(class_scope:DataPoint)
  ))
_sym_db.RegisterMessage(DataPoint)

Scan = _reflection.GeneratedProtocolMessageType('Scan', (_message.Message,), dict(
  DESCRIPTOR = _SCAN,
  __module__ = 'car_protobufs.lidar_proto_pb2'
  # @@protoc_insertion_point(class_scope:Scan)
  ))
_sym_db.RegisterMessage(Scan)

HealthRequest = _reflection.GeneratedProtocolMessageType('HealthRequest', (_message.Message,), dict(
  DESCRIPTOR = _HEALTHREQUEST,
  __module__ = 'car_protobufs.lidar_proto_pb2'
  # @@protoc_insertion_point(class_scope:HealthRequest)
  ))
_sym_db.RegisterMessage(HealthRequest)

HealthStatus = _reflection.GeneratedProtocolMessageType('HealthStatus', (_message.Message,), dict(
  DESCRIPTOR = _HEALTHSTATUS,
  __module__ = 'car_protobufs.lidar_proto_pb2'
  # @@protoc_insertion_point(class_scope:HealthStatus)
  ))
_sym_db.RegisterMessage(HealthStatus)


# @@protoc_insertion_point(module_scope)
