# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: car_protobufs/signal_protobuf.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='car_protobufs/signal_protobuf.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n#car_protobufs/signal_protobuf.proto\":\n\x0b\x43\x41N_Signals\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x12\x18\n\x07signals\x18\x02 \x03(\x0b\x32\x07.Signal\"r\n\x06Signal\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x15\n\x0bstring_data\x18\x02 \x01(\tH\x00\x12\x14\n\nfloat_data\x18\x03 \x01(\x02H\x00\x12\x12\n\x08int_data\x18\x04 \x01(\x05H\x00\x12\x13\n\tbool_data\x18\x05 \x01(\x08H\x00\x42\x06\n\x04\x64\x61ta\"\x1b\n\x05Image\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x62\x06proto3')
)




_CAN_SIGNALS = _descriptor.Descriptor(
  name='CAN_Signals',
  full_name='CAN_Signals',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='CAN_Signals.timestamp', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='signals', full_name='CAN_Signals.signals', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=97,
)


_SIGNAL = _descriptor.Descriptor(
  name='Signal',
  full_name='Signal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Signal.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='string_data', full_name='Signal.string_data', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='float_data', full_name='Signal.float_data', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='int_data', full_name='Signal.int_data', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bool_data', full_name='Signal.bool_data', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='data', full_name='Signal.data',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=99,
  serialized_end=213,
)


_IMAGE = _descriptor.Descriptor(
  name='Image',
  full_name='Image',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image_data', full_name='Image.image_data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=215,
  serialized_end=242,
)

_CAN_SIGNALS.fields_by_name['signals'].message_type = _SIGNAL
_SIGNAL.oneofs_by_name['data'].fields.append(
  _SIGNAL.fields_by_name['string_data'])
_SIGNAL.fields_by_name['string_data'].containing_oneof = _SIGNAL.oneofs_by_name['data']
_SIGNAL.oneofs_by_name['data'].fields.append(
  _SIGNAL.fields_by_name['float_data'])
_SIGNAL.fields_by_name['float_data'].containing_oneof = _SIGNAL.oneofs_by_name['data']
_SIGNAL.oneofs_by_name['data'].fields.append(
  _SIGNAL.fields_by_name['int_data'])
_SIGNAL.fields_by_name['int_data'].containing_oneof = _SIGNAL.oneofs_by_name['data']
_SIGNAL.oneofs_by_name['data'].fields.append(
  _SIGNAL.fields_by_name['bool_data'])
_SIGNAL.fields_by_name['bool_data'].containing_oneof = _SIGNAL.oneofs_by_name['data']
DESCRIPTOR.message_types_by_name['CAN_Signals'] = _CAN_SIGNALS
DESCRIPTOR.message_types_by_name['Signal'] = _SIGNAL
DESCRIPTOR.message_types_by_name['Image'] = _IMAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CAN_Signals = _reflection.GeneratedProtocolMessageType('CAN_Signals', (_message.Message,), dict(
  DESCRIPTOR = _CAN_SIGNALS,
  __module__ = 'car_protobufs.signal_protobuf_pb2'
  # @@protoc_insertion_point(class_scope:CAN_Signals)
  ))
_sym_db.RegisterMessage(CAN_Signals)

Signal = _reflection.GeneratedProtocolMessageType('Signal', (_message.Message,), dict(
  DESCRIPTOR = _SIGNAL,
  __module__ = 'car_protobufs.signal_protobuf_pb2'
  # @@protoc_insertion_point(class_scope:Signal)
  ))
_sym_db.RegisterMessage(Signal)

Image = _reflection.GeneratedProtocolMessageType('Image', (_message.Message,), dict(
  DESCRIPTOR = _IMAGE,
  __module__ = 'car_protobufs.signal_protobuf_pb2'
  # @@protoc_insertion_point(class_scope:Image)
  ))
_sym_db.RegisterMessage(Image)


# @@protoc_insertion_point(module_scope)
